# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1suMftWoqzuHgg3GjrwOKf8V5TRJ_0W7m
"""









def fun(a):
    if a % 2 == 0:
       return True
    else:
       return False
list1 = [1, 2, 3, 4, 5]
list2 = filter(fun, list1)
print(list(list2))